name: Android CI/CD with MobSF

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Start MobSF in Docker
        run: docker compose up -d
      
      - name: Wait for MobSF to be ready
        run: sleep 60

      - name: Upload APK to MobSF
        run: |
          APK_FILE=$(find $GITHUB_WORKSPACE/app/build/outputs/apk/debug/ -name "*.apk" | head -n 1)
          echo "Uploading $APK_FILE to MobSF"
          curl -F "file=@${APK_FILE}" http://localhost:8000/api/v1/upload -H "Authorization: ${{ secrets.MOBSF_API_KEY }}" -o mobsf_output.json

      - name: Get MobSF scan results
        run: |
          APK_HASH=$(jq -r .hash mobsf_output.json)
          curl http://localhost:8000/api/v1/report_json?md5=${APK_HASH} -H "Authorization: ${{ secrets.MOBSF_API_KEY }}" -o mobsf_report.json
          
      - name: Save MobSF report
        uses: actions/upload-artifact@v2
        with:
          name: mobsf-report
          path: mobsf_report.json

      - name: Stop MobSF Docker
        run: docker-compose down

